import React from 'react';
import { GoabTemporaryNotificationCtrl, GoabButton } from '@abgov/react-components';
import { TemporaryNotification } from "@abgov/ui-components-common";

// This component tests the code snippets generated by our documentation
export function TemporaryNotificationSandbox() {
  
  // In your component
  const showNotification = () => {
    TemporaryNotification.show("This is a notification message from Vaness", {
      type: "basic",
      duration: "medium",
      actionText: "Dismiss",
      action: () => {
        TemporaryNotification.show("Action performed!", { type: "success", duration: 2000 });
      }
    });
  };

  return (
    <div style={{ padding: '20px' }}>
      <h1>Temporary Notification Sandbox</h1>
      <p>Testing the generated code snippets from the documentation</p>
      
      <GoabButton onClick={showNotification}>
        Show Notification
      </GoabButton>
      
      {/* The controller component as shown in the first code snippet */}
      <GoabTemporaryNotificationCtrl 
        verticalPosition="bottom" 
        horizontalPosition="center" 
      />
    </div>
  );
}
